version: "3"
services:
  app:
    image: node:12.18.2
    container_name: container_node_discord_bot
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: bash -c "npm install && npm start"
    tty: true
    stdin_open: false
    links:
      - mariadb

  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    container_name: container_mariadb_discord_bot
    environment:
      MYSQL_DATABASE: discord_bot
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
